In [1]:
import pandas as pd
import numpy as np

# Data Gathering

In [2]:
df=pd.read_csv('Covid19India1.csv')

In [3]:
df.head()

Unnamed: 0  Num Cases Date Announced  Age Bracket Gender  \
0           0        1.0     30/01/2020         20.0      F   
1           1        1.0       2/2/2020          NaN    NaN   
2           2        1.0       3/2/2020          NaN    NaN   
3           3        1.0       2/3/2020         45.0      M   
4           4        1.0       2/3/2020         24.0      M   

              Detected City Detected District Detected State Current Status  \
0                  Thrissur          Thrissur         Kerala      Recovered   
1                 Alappuzha         Alappuzha         Kerala      Recovered   
2                 Kasaragod         Kasaragod         Kerala      Recovered   
3  East Delhi (Mayur Vihar)        East Delhi          Delhi      Recovered   
4                 Hyderabad         Hyderabad      Telangana      Recovered   

   Day  Month  Year  
0   30      1  2020  
1    2      2  2020  
2    3      2  2020  
3    2      3  2020  
4    2      3  2020

In [4]:
df=df.drop(['Date Announced'],axis=1)

In [5]:
df.rename(columns={"Unnamed: 0": "Id"},inplace=True)


In [6]:
df.head()

Id  Num Cases  Age Bracket Gender             Detected City  \
0   0        1.0         20.0      F                  Thrissur   
1   1        1.0          NaN    NaN                 Alappuzha   
2   2        1.0          NaN    NaN                 Kasaragod   
3   3        1.0         45.0      M  East Delhi (Mayur Vihar)   
4   4        1.0         24.0      M                 Hyderabad   

  Detected District Detected State Current Status  Day  Month  Year  
0          Thrissur         Kerala      Recovered   30      1  2020  
1         Alappuzha         Kerala      Recovered    2      2  2020  
2         Kasaragod         Kerala      Recovered    3      2  2020  
3        East Delhi          Delhi      Recovered    2      3  2020  
4         Hyderabad      Telangana      Recovered    2      3  2020

# Checking Null Values

In [8]:
df.isnull().sum()

Id                        0
Num Cases                 3
Age Bracket          137125
Gender               134101
Detected City        245015
Detected District      9593
Detected State            9
Current Status            2
Day                       0
Month                     0
Year                      0
dtype: int64

# Filling Null values in Catagorical Column

In [9]:
df['Gender']=df['Gender'].fillna('No gender')
df['Gender'].isnull().sum()

0

In [10]:
df['Detected City']=df['Detected City'].fillna('Notmentioned')
df['Detected City'].isnull().sum()

0

In [11]:
df['Detected District']=df['Detected District'].fillna('Notmentioned')
df['Detected District'].isnull().sum()

0

In [12]:
df['Detected State']=df['Detected State'].fillna('Not')
df['Detected State'].isnull().sum()

0

In [13]:
df['Current Status']=df['Current Status'].fillna('No')
df['Current Status'].isnull().sum()

0

# Filling Null Values in Numerical Column

In [35]:
df['Age Bracket']=df['Age Bracket'].fillna(0)


In [17]:
df['Num Cases'] = df['Num Cases'].fillna(0)

In [18]:
df['Day'] = df['Day'].fillna(0)

In [19]:
df['Month'] = df['Month'].fillna(0)

In [20]:
df['Year'] = df['Year'].fillna(0)

In [21]:
df['Id'] = df['Id'].fillna(0)

In [22]:
df.isnull().sum()

Id                   0
Num Cases            0
Age Bracket          0
Gender               0
Detected City        0
Detected District    0
Detected State       0
Current Status       0
Day                  0
Month                0
Year                 0
dtype: int64

# Label encoding
sklearn require all inputs are in numeric so we are using label encoding for convert
catagorical column in numeric
Label Encoding is a popular encoding technique for handling categorical variables. 
In this technique, each label is assigned a unique integer based on alphabetical ordering


In [23]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Gender','Detected City','Detected District','Detected State','Current Status']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i])

# Data splitting in x and y

In [24]:
y = df["Current Status"]
x = df.drop('Current Status',axis=1)

# Classification Model

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn import metrics


In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)
print(x_train.shape)
print(x_test.shape)

(207859, 10)
(51965, 10)


# 1.Logistic Regression Without cross validation

In [32]:
model = LogisticRegression()
model.fit(x_train,y_train)
predictions = model.predict(x_test)
print(accuracy_score(y_test, predictions))

0.8034253824689696


# Logistic Regression With Cross Validation

In [33]:
#With CV 
cv_score=cross_val_score(model,x,y,cv=10)
print("Accuracy with Cross Validation:",np.mean(cv_score))

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Accuracy with Cross Validation: 0.7667480363712139


# 2. RandomForestClassifier without CV

In [36]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(x_train,y_train)
predictions = rfc.predict(x_test)
print(accuracy_score(y_test, predictions))

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


0.9472337150004811


# Random Forest with CV

In [37]:
#Without CV & without Feature Selection
cv_score=cross_val_score(rfc,x,y,cv=10)
print("Accuracy:",np.mean(cv_score))

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Accuracy: 0.7591383961449967


# 3. Knn without CV

In [41]:
import numpy as np
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report

knn = KNeighborsClassifier(n_neighbors=17)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print ("K-NN Classification Accuracy: ",metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

K-NN Classification Accuracy:  0.8731453863177139
[[  651   851     0     0     0   323]
 [  160 36568     0     2     0  1661]
 [    0     1     0     0     0     0]
 [    1    21     0     0     0     9]
 [    0     1     0     0     0     0]
 [  149  3412     0     1     0  8154]]
             precision    recall  f1-score   support

          0       0.68      0.36      0.47      1825
          1       0.90      0.95      0.92     38391
          2       0.00      0.00      0.00         1
          3       0.00      0.00      0.00        31
          4       0.00      0.00      0.00         1
          6       0.80      0.70      0.75     11716

avg / total       0.87      0.87      0.87     51965



C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [42]:
#With CV 
cv_score=cross_val_score(knn,x,y,cv=10)
print("Accuracy with Cross Validation:",np.mean(cv_score))

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Accuracy with Cross Validation: 0.8026944009383792


# 4.Decision Tree without CV

In [39]:
from sklearn import tree

dtree = tree.DecisionTreeClassifier(random_state=6)
dtree.fit(x_train, y_train)

y_pred = dtree.predict(x_test)
print (y_pred)
print ("Decision Tree Accuracy: ",metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[1 1 1 ... 6 1 1]
Decision Tree Accuracy:  0.9519869142692197
[[ 1467   211     0     1     0   146]
 [  220 37307     0     3     0   861]
 [    0     1     0     0     0     0]
 [    1     6     0    22     0     2]
 [    0     0     0     0     1     0]
 [  152   887     0     3     1 10673]]
             precision    recall  f1-score   support

          0       0.80      0.80      0.80      1825
          1       0.97      0.97      0.97     38391
          2       0.00      0.00      0.00         1
          3       0.76      0.71      0.73        31
          4       0.50      1.00      0.67         1
          6       0.91      0.91      0.91     11716

avg / total       0.95      0.95      0.95     51965



C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [40]:
#With CV 
cv_score=cross_val_score(dtree,x,y,cv=10)
print("Accuracy with Cross Validation:",np.mean(cv_score))

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Accuracy with Cross Validation: 0.7592344680653191


# 5.Adaboost Without CV

In [43]:
#Without CV & without Feature Selection
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
adb=AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=100)
adb.fit(x_train,y_train)
y_pred=adb.predict(x_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Confusion Matrix:\n",classification_report(y_test,y_pred))

Accuracy: 0.80159722890407
Confusion Matrix:
 [[    0   733     0     0     0  1092]
 [    0 31492     0     0     0  6899]
 [    0     1     0     0     0     0]
 [    0     3     0     0     0    28]
 [    0     1     0     0     0     0]
 [    0  1553     0     0     0 10163]]
Confusion Matrix:
              precision    recall  f1-score   support

          0       0.00      0.00      0.00      1825
          1       0.93      0.82      0.87     38391
          2       0.00      0.00      0.00         1
          3       0.00      0.00      0.00        31
          4       0.00      0.00      0.00         1
          6       0.56      0.87      0.68     11716

avg / total       0.81      0.80      0.80     51965



C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Adboost With CV

In [44]:
#Without CV 
adb=AdaBoostClassifier()
cv_score=cross_val_score(adb,x,y,cv=10)
print("Accuracy:",np.mean(cv_score))

C:\Users\Sony\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


Accuracy: 0.7567304858034167
